version: '3.2'

services:
  php:
    build: ./docker/php-fpm-alpine
    image: marm-app-sync
    container_name: marm-app-sync
    volumes:
      - .:/var/www/mc
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    networks:
      - default
      - marm-db

  nginx:
    build: ./docker/nginx
    image: marm-server-sync
    container_name: marm-server-sync
    volumes:
      - .:/var/www/mc
    ports:
      - "8050:80"
    depends_on:
      - php
    networks:
      - default
      - marm-cms

networks:
  marm-db:
    external: true
  marm-cms:
    external: true